<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="sarada-HP-255-G6-Notebook-PC" failures="1" tests="4" name="Default test(failed)" time="0.108" errors="0" timestamp="19 Apr 2020 13:23:23 GMT">
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod3" time="0.023">
    <skipped/>
  </testcase> <!-- testmethod3 -->
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod3" time="0.003">
    <skipped/>
  </testcase> <!-- testmethod3 -->
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod3" time="0.003">
    <skipped/>
  </testcase> <!-- testmethod3 -->
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod3" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryFailedTests.RetryfailedTests.testmethod3(RetryfailedTests.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testmethod3 -->
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod1" time="0.0">
    <ignored/>
  </testcase> <!-- testmethod1 -->
  <testcase classname="RetryFailedTests.RetryfailedTests" name="testmethod2" time="0.0">
    <ignored/>
  </testcase> <!-- testmethod2 -->
</testsuite> <!-- Default test(failed) -->
